version: "3"

services:
  db:
    build:
      context: ./DockerPostgresql
      dockerfile: db.Dockerfile
    container_name: db
    networks:
      - challenge
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 55432:5432
  backend:
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend  
    networks:
      - challenge
    depends_on:
      - db
networks:
  challenge:

